/*
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JavaliAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("pt/iscte/paddle/parser/antlr/internal/InternalJavali.tokens");
	}
}
