/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Break</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.iscte.paddle.javali.JavaliPackage#getBreak()
 * @model
 * @generated
 */
public interface Break extends Statement
{
} // Break
