/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see pt.iscte.paddle.javali.JavaliFactory
 * @model kind="package"
 * @generated
 */
public interface JavaliPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "javali";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.iscte.pt/paddle/Javali";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "javali";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  JavaliPackage eINSTANCE = pt.iscte.paddle.javali.impl.JavaliPackageImpl.init();

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ModuleImpl <em>Module</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ModuleImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getModule()
   * @generated
   */
  int MODULE = 0;

  /**
   * The feature id for the '<em><b>Constants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__CONSTANTS = 0;

  /**
   * The feature id for the '<em><b>Records</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__RECORDS = 1;

  /**
   * The feature id for the '<em><b>Procedures</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE__PROCEDURES = 2;

  /**
   * The number of structural features of the '<em>Module</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ConstantImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 1;

  /**
   * The feature id for the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__STATIC = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__TYPE = 1;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__ID = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__VALUE = 3;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.RecordImpl <em>Record</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.RecordImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getRecord()
   * @generated
   */
  int RECORD = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD__ID = 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD__FIELDS = 1;

  /**
   * The number of structural features of the '<em>Record</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ProcedureImpl <em>Procedure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ProcedureImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getProcedure()
   * @generated
   */
  int PROCEDURE = 3;

  /**
   * The feature id for the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__COMMENT = 0;

  /**
   * The feature id for the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__STATIC = 1;

  /**
   * The feature id for the '<em><b>Ret Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__RET_TYPE = 2;

  /**
   * The feature id for the '<em><b>Void</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__VOID = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__ID = 4;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__PARAMS = 5;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__BODY = 6;

  /**
   * The number of structural features of the '<em>Procedure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.BlockImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 4;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.StatementImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 5;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ReturnImpl <em>Return</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ReturnImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getReturn()
   * @generated
   */
  int RETURN = 6;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN__EXP = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Return</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURN_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.BreakImpl <em>Break</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.BreakImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getBreak()
   * @generated
   */
  int BREAK = 7;

  /**
   * The number of structural features of the '<em>Break</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREAK_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ContinueImpl <em>Continue</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ContinueImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getContinue()
   * @generated
   */
  int CONTINUE = 8;

  /**
   * The number of structural features of the '<em>Continue</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTINUE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.VarDeclarationImpl <em>Var Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.VarDeclarationImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getVarDeclaration()
   * @generated
   */
  int VAR_DECLARATION = 9;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__TYPE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__ID = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__INIT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Var Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.VarAssignImpl <em>Var Assign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.VarAssignImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getVarAssign()
   * @generated
   */
  int VAR_ASSIGN = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_ASSIGN__VAR = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_ASSIGN__EXP = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Var Assign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_ASSIGN_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.IfElseImpl <em>If Else</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.IfElseImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getIfElse()
   * @generated
   */
  int IF_ELSE = 11;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_ELSE__GUARD = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selection Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_ELSE__SELECTION_BLOCK = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Alternative Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_ELSE__ALTERNATIVE_BLOCK = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Else</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_ELSE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.WhileImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 12;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__GUARD = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__BLOCK = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ForImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getFor()
   * @generated
   */
  int FOR = 13;

  /**
   * The feature id for the '<em><b>Init Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__INIT_STATEMENTS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__GUARD = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Progress Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__PROGRESS_STATEMENTS = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__BLOCK = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.DoWhileImpl <em>Do While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.DoWhileImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getDoWhile()
   * @generated
   */
  int DO_WHILE = 14;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_WHILE__BLOCK = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_WHILE__GUARD = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Do While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_WHILE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.IncrementImpl <em>Increment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.IncrementImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getIncrement()
   * @generated
   */
  int INCREMENT = 15;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT__ID = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Increment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.DecrementImpl <em>Decrement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.DecrementImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getDecrement()
   * @generated
   */
  int DECREMENT = 16;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECREMENT__ID = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Decrement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECREMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ExpressionImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 17;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.LiteralImpl <em>Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.LiteralImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getLiteral()
   * @generated
   */
  int LITERAL = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.NullImpl <em>Null</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.NullImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getNull()
   * @generated
   */
  int NULL = 19;

  /**
   * The number of structural features of the '<em>Null</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NULL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.VarExpressionImpl <em>Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.VarExpressionImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getVarExpression()
   * @generated
   */
  int VAR_EXPRESSION = 20;

  /**
   * The feature id for the '<em><b>Parts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_EXPRESSION__PARTS = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Array Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_EXPRESSION__ARRAY_INDEXES = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.ProcCallImpl <em>Proc Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.ProcCallImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getProcCall()
   * @generated
   */
  int PROC_CALL = 21;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROC_CALL__ID = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROC_CALL__ARGS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Proc Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROC_CALL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.TypeImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getType()
   * @generated
   */
  int TYPE = 22;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__ID = 0;

  /**
   * The feature id for the '<em><b>Array Dims</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__ARRAY_DIMS = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.NewArrayImpl <em>New Array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.NewArrayImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getNewArray()
   * @generated
   */
  int NEW_ARRAY = 23;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_ARRAY__TYPE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Array Dims</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_ARRAY__ARRAY_DIMS = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>New Array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_ARRAY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.NewObjectImpl <em>New Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.NewObjectImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getNewObject()
   * @generated
   */
  int NEW_OBJECT = 24;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_OBJECT__TYPE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>New Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_OBJECT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.IdentifierImpl <em>Identifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.IdentifierImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getIdentifier()
   * @generated
   */
  int IDENTIFIER = 25;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFIER__ID = 0;

  /**
   * The number of structural features of the '<em>Identifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFIER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.OrImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getOr()
   * @generated
   */
  int OR = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.XorImpl <em>Xor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.XorImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getXor()
   * @generated
   */
  int XOR = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Xor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.AndImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getAnd()
   * @generated
   */
  int AND = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.EqualityImpl <em>Equality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.EqualityImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getEquality()
   * @generated
   */
  int EQUALITY = 29;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Equality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.RelationImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 30;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.AdditionImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 31;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link pt.iscte.paddle.javali.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pt.iscte.paddle.javali.impl.MultiplicationImpl
   * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 32;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Module <em>Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module</em>'.
   * @see pt.iscte.paddle.javali.Module
   * @generated
   */
  EClass getModule();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.Module#getConstants <em>Constants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constants</em>'.
   * @see pt.iscte.paddle.javali.Module#getConstants()
   * @see #getModule()
   * @generated
   */
  EReference getModule_Constants();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.Module#getRecords <em>Records</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Records</em>'.
   * @see pt.iscte.paddle.javali.Module#getRecords()
   * @see #getModule()
   * @generated
   */
  EReference getModule_Records();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.Module#getProcedures <em>Procedures</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Procedures</em>'.
   * @see pt.iscte.paddle.javali.Module#getProcedures()
   * @see #getModule()
   * @generated
   */
  EReference getModule_Procedures();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see pt.iscte.paddle.javali.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Constant#isStatic <em>Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Static</em>'.
   * @see pt.iscte.paddle.javali.Constant#isStatic()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Static();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Constant#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see pt.iscte.paddle.javali.Constant#getType()
   * @see #getConstant()
   * @generated
   */
  EReference getConstant_Type();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Constant#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Constant#getId()
   * @see #getConstant()
   * @generated
   */
  EReference getConstant_Id();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Constant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see pt.iscte.paddle.javali.Constant#getValue()
   * @see #getConstant()
   * @generated
   */
  EReference getConstant_Value();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Record <em>Record</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Record</em>'.
   * @see pt.iscte.paddle.javali.Record
   * @generated
   */
  EClass getRecord();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Record#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Record#getId()
   * @see #getRecord()
   * @generated
   */
  EReference getRecord_Id();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.Record#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see pt.iscte.paddle.javali.Record#getFields()
   * @see #getRecord()
   * @generated
   */
  EReference getRecord_Fields();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Procedure <em>Procedure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Procedure</em>'.
   * @see pt.iscte.paddle.javali.Procedure
   * @generated
   */
  EClass getProcedure();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Procedure#getComment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comment</em>'.
   * @see pt.iscte.paddle.javali.Procedure#getComment()
   * @see #getProcedure()
   * @generated
   */
  EAttribute getProcedure_Comment();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Procedure#isStatic <em>Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Static</em>'.
   * @see pt.iscte.paddle.javali.Procedure#isStatic()
   * @see #getProcedure()
   * @generated
   */
  EAttribute getProcedure_Static();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Procedure#getRetType <em>Ret Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ret Type</em>'.
   * @see pt.iscte.paddle.javali.Procedure#getRetType()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_RetType();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Procedure#isVoid <em>Void</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Void</em>'.
   * @see pt.iscte.paddle.javali.Procedure#isVoid()
   * @see #getProcedure()
   * @generated
   */
  EAttribute getProcedure_Void();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Procedure#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Procedure#getId()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Id();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.Procedure#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see pt.iscte.paddle.javali.Procedure#getParams()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Params();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Procedure#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see pt.iscte.paddle.javali.Procedure#getBody()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Body();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see pt.iscte.paddle.javali.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.Block#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see pt.iscte.paddle.javali.Block#getStatements()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Statements();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see pt.iscte.paddle.javali.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Return <em>Return</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Return</em>'.
   * @see pt.iscte.paddle.javali.Return
   * @generated
   */
  EClass getReturn();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Return#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see pt.iscte.paddle.javali.Return#getExp()
   * @see #getReturn()
   * @generated
   */
  EReference getReturn_Exp();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Break <em>Break</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Break</em>'.
   * @see pt.iscte.paddle.javali.Break
   * @generated
   */
  EClass getBreak();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Continue <em>Continue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Continue</em>'.
   * @see pt.iscte.paddle.javali.Continue
   * @generated
   */
  EClass getContinue();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.VarDeclaration <em>Var Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Declaration</em>'.
   * @see pt.iscte.paddle.javali.VarDeclaration
   * @generated
   */
  EClass getVarDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.VarDeclaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see pt.iscte.paddle.javali.VarDeclaration#getType()
   * @see #getVarDeclaration()
   * @generated
   */
  EReference getVarDeclaration_Type();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.VarDeclaration#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.VarDeclaration#getId()
   * @see #getVarDeclaration()
   * @generated
   */
  EReference getVarDeclaration_Id();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.VarDeclaration#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see pt.iscte.paddle.javali.VarDeclaration#getInit()
   * @see #getVarDeclaration()
   * @generated
   */
  EReference getVarDeclaration_Init();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.VarAssign <em>Var Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Assign</em>'.
   * @see pt.iscte.paddle.javali.VarAssign
   * @generated
   */
  EClass getVarAssign();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.VarAssign#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see pt.iscte.paddle.javali.VarAssign#getVar()
   * @see #getVarAssign()
   * @generated
   */
  EReference getVarAssign_Var();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.VarAssign#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see pt.iscte.paddle.javali.VarAssign#getExp()
   * @see #getVarAssign()
   * @generated
   */
  EReference getVarAssign_Exp();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.IfElse <em>If Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Else</em>'.
   * @see pt.iscte.paddle.javali.IfElse
   * @generated
   */
  EClass getIfElse();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.IfElse#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see pt.iscte.paddle.javali.IfElse#getGuard()
   * @see #getIfElse()
   * @generated
   */
  EReference getIfElse_Guard();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.IfElse#getSelectionBlock <em>Selection Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selection Block</em>'.
   * @see pt.iscte.paddle.javali.IfElse#getSelectionBlock()
   * @see #getIfElse()
   * @generated
   */
  EReference getIfElse_SelectionBlock();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.IfElse#getAlternativeBlock <em>Alternative Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alternative Block</em>'.
   * @see pt.iscte.paddle.javali.IfElse#getAlternativeBlock()
   * @see #getIfElse()
   * @generated
   */
  EReference getIfElse_AlternativeBlock();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see pt.iscte.paddle.javali.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.While#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see pt.iscte.paddle.javali.While#getGuard()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Guard();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.While#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see pt.iscte.paddle.javali.While#getBlock()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Block();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see pt.iscte.paddle.javali.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.For#getInitStatements <em>Init Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Init Statements</em>'.
   * @see pt.iscte.paddle.javali.For#getInitStatements()
   * @see #getFor()
   * @generated
   */
  EReference getFor_InitStatements();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.For#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see pt.iscte.paddle.javali.For#getGuard()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Guard();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.For#getProgressStatements <em>Progress Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Progress Statements</em>'.
   * @see pt.iscte.paddle.javali.For#getProgressStatements()
   * @see #getFor()
   * @generated
   */
  EReference getFor_ProgressStatements();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.For#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see pt.iscte.paddle.javali.For#getBlock()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Block();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.DoWhile <em>Do While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Do While</em>'.
   * @see pt.iscte.paddle.javali.DoWhile
   * @generated
   */
  EClass getDoWhile();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.DoWhile#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see pt.iscte.paddle.javali.DoWhile#getBlock()
   * @see #getDoWhile()
   * @generated
   */
  EReference getDoWhile_Block();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.DoWhile#getGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Guard</em>'.
   * @see pt.iscte.paddle.javali.DoWhile#getGuard()
   * @see #getDoWhile()
   * @generated
   */
  EReference getDoWhile_Guard();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Increment <em>Increment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Increment</em>'.
   * @see pt.iscte.paddle.javali.Increment
   * @generated
   */
  EClass getIncrement();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Increment#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Increment#getId()
   * @see #getIncrement()
   * @generated
   */
  EReference getIncrement_Id();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Decrement <em>Decrement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decrement</em>'.
   * @see pt.iscte.paddle.javali.Decrement
   * @generated
   */
  EClass getDecrement();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Decrement#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Decrement#getId()
   * @see #getDecrement()
   * @generated
   */
  EReference getDecrement_Id();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see pt.iscte.paddle.javali.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Literal <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal</em>'.
   * @see pt.iscte.paddle.javali.Literal
   * @generated
   */
  EClass getLiteral();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Literal#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see pt.iscte.paddle.javali.Literal#getValue()
   * @see #getLiteral()
   * @generated
   */
  EAttribute getLiteral_Value();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Null <em>Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Null</em>'.
   * @see pt.iscte.paddle.javali.Null
   * @generated
   */
  EClass getNull();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.VarExpression <em>Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Expression</em>'.
   * @see pt.iscte.paddle.javali.VarExpression
   * @generated
   */
  EClass getVarExpression();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.VarExpression#getParts <em>Parts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parts</em>'.
   * @see pt.iscte.paddle.javali.VarExpression#getParts()
   * @see #getVarExpression()
   * @generated
   */
  EReference getVarExpression_Parts();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.VarExpression#getArrayIndexes <em>Array Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Array Indexes</em>'.
   * @see pt.iscte.paddle.javali.VarExpression#getArrayIndexes()
   * @see #getVarExpression()
   * @generated
   */
  EReference getVarExpression_ArrayIndexes();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.ProcCall <em>Proc Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Proc Call</em>'.
   * @see pt.iscte.paddle.javali.ProcCall
   * @generated
   */
  EClass getProcCall();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.ProcCall#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.ProcCall#getId()
   * @see #getProcCall()
   * @generated
   */
  EReference getProcCall_Id();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.ProcCall#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see pt.iscte.paddle.javali.ProcCall#getArgs()
   * @see #getProcCall()
   * @generated
   */
  EReference getProcCall_Args();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see pt.iscte.paddle.javali.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Type#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Type#getId()
   * @see #getType()
   * @generated
   */
  EReference getType_Id();

  /**
   * Returns the meta object for the attribute list '{@link pt.iscte.paddle.javali.Type#getArrayDims <em>Array Dims</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Array Dims</em>'.
   * @see pt.iscte.paddle.javali.Type#getArrayDims()
   * @see #getType()
   * @generated
   */
  EAttribute getType_ArrayDims();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.NewArray <em>New Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>New Array</em>'.
   * @see pt.iscte.paddle.javali.NewArray
   * @generated
   */
  EClass getNewArray();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.NewArray#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see pt.iscte.paddle.javali.NewArray#getType()
   * @see #getNewArray()
   * @generated
   */
  EReference getNewArray_Type();

  /**
   * Returns the meta object for the containment reference list '{@link pt.iscte.paddle.javali.NewArray#getArrayDims <em>Array Dims</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Array Dims</em>'.
   * @see pt.iscte.paddle.javali.NewArray#getArrayDims()
   * @see #getNewArray()
   * @generated
   */
  EReference getNewArray_ArrayDims();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.NewObject <em>New Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>New Object</em>'.
   * @see pt.iscte.paddle.javali.NewObject
   * @generated
   */
  EClass getNewObject();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.NewObject#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see pt.iscte.paddle.javali.NewObject#getType()
   * @see #getNewObject()
   * @generated
   */
  EReference getNewObject_Type();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Identifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Identifier</em>'.
   * @see pt.iscte.paddle.javali.Identifier
   * @generated
   */
  EClass getIdentifier();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Identifier#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see pt.iscte.paddle.javali.Identifier#getId()
   * @see #getIdentifier()
   * @generated
   */
  EAttribute getIdentifier_Id();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see pt.iscte.paddle.javali.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Xor <em>Xor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xor</em>'.
   * @see pt.iscte.paddle.javali.Xor
   * @generated
   */
  EClass getXor();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Xor#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.Xor#getLeft()
   * @see #getXor()
   * @generated
   */
  EReference getXor_Left();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Xor#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.Xor#getRight()
   * @see #getXor()
   * @generated
   */
  EReference getXor_Right();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see pt.iscte.paddle.javali.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Equality <em>Equality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equality</em>'.
   * @see pt.iscte.paddle.javali.Equality
   * @generated
   */
  EClass getEquality();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Equality#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.Equality#getLeft()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Left();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Equality#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see pt.iscte.paddle.javali.Equality#getOperator()
   * @see #getEquality()
   * @generated
   */
  EAttribute getEquality_Operator();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Equality#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.Equality#getRight()
   * @see #getEquality()
   * @generated
   */
  EReference getEquality_Right();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see pt.iscte.paddle.javali.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Relation#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.Relation#getLeft()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Left();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Relation#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see pt.iscte.paddle.javali.Relation#getOperator()
   * @see #getRelation()
   * @generated
   */
  EAttribute getRelation_Operator();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Relation#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.Relation#getRight()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Right();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see pt.iscte.paddle.javali.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see pt.iscte.paddle.javali.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link pt.iscte.paddle.javali.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see pt.iscte.paddle.javali.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see pt.iscte.paddle.javali.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute '{@link pt.iscte.paddle.javali.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see pt.iscte.paddle.javali.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference '{@link pt.iscte.paddle.javali.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see pt.iscte.paddle.javali.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  JavaliFactory getJavaliFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ModuleImpl <em>Module</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ModuleImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getModule()
     * @generated
     */
    EClass MODULE = eINSTANCE.getModule();

    /**
     * The meta object literal for the '<em><b>Constants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__CONSTANTS = eINSTANCE.getModule_Constants();

    /**
     * The meta object literal for the '<em><b>Records</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__RECORDS = eINSTANCE.getModule_Records();

    /**
     * The meta object literal for the '<em><b>Procedures</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULE__PROCEDURES = eINSTANCE.getModule_Procedures();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ConstantImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__STATIC = eINSTANCE.getConstant_Static();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANT__TYPE = eINSTANCE.getConstant_Type();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANT__ID = eINSTANCE.getConstant_Id();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANT__VALUE = eINSTANCE.getConstant_Value();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.RecordImpl <em>Record</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.RecordImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getRecord()
     * @generated
     */
    EClass RECORD = eINSTANCE.getRecord();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECORD__ID = eINSTANCE.getRecord_Id();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECORD__FIELDS = eINSTANCE.getRecord_Fields();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ProcedureImpl <em>Procedure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ProcedureImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getProcedure()
     * @generated
     */
    EClass PROCEDURE = eINSTANCE.getProcedure();

    /**
     * The meta object literal for the '<em><b>Comment</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE__COMMENT = eINSTANCE.getProcedure_Comment();

    /**
     * The meta object literal for the '<em><b>Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE__STATIC = eINSTANCE.getProcedure_Static();

    /**
     * The meta object literal for the '<em><b>Ret Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__RET_TYPE = eINSTANCE.getProcedure_RetType();

    /**
     * The meta object literal for the '<em><b>Void</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE__VOID = eINSTANCE.getProcedure_Void();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__ID = eINSTANCE.getProcedure_Id();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__PARAMS = eINSTANCE.getProcedure_Params();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__BODY = eINSTANCE.getProcedure_Body();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.BlockImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__STATEMENTS = eINSTANCE.getBlock_Statements();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.StatementImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ReturnImpl <em>Return</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ReturnImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getReturn()
     * @generated
     */
    EClass RETURN = eINSTANCE.getReturn();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RETURN__EXP = eINSTANCE.getReturn_Exp();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.BreakImpl <em>Break</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.BreakImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getBreak()
     * @generated
     */
    EClass BREAK = eINSTANCE.getBreak();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ContinueImpl <em>Continue</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ContinueImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getContinue()
     * @generated
     */
    EClass CONTINUE = eINSTANCE.getContinue();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.VarDeclarationImpl <em>Var Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.VarDeclarationImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getVarDeclaration()
     * @generated
     */
    EClass VAR_DECLARATION = eINSTANCE.getVarDeclaration();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECLARATION__TYPE = eINSTANCE.getVarDeclaration_Type();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECLARATION__ID = eINSTANCE.getVarDeclaration_Id();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECLARATION__INIT = eINSTANCE.getVarDeclaration_Init();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.VarAssignImpl <em>Var Assign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.VarAssignImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getVarAssign()
     * @generated
     */
    EClass VAR_ASSIGN = eINSTANCE.getVarAssign();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_ASSIGN__VAR = eINSTANCE.getVarAssign_Var();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_ASSIGN__EXP = eINSTANCE.getVarAssign_Exp();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.IfElseImpl <em>If Else</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.IfElseImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getIfElse()
     * @generated
     */
    EClass IF_ELSE = eINSTANCE.getIfElse();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_ELSE__GUARD = eINSTANCE.getIfElse_Guard();

    /**
     * The meta object literal for the '<em><b>Selection Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_ELSE__SELECTION_BLOCK = eINSTANCE.getIfElse_SelectionBlock();

    /**
     * The meta object literal for the '<em><b>Alternative Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_ELSE__ALTERNATIVE_BLOCK = eINSTANCE.getIfElse_AlternativeBlock();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.WhileImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__GUARD = eINSTANCE.getWhile_Guard();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__BLOCK = eINSTANCE.getWhile_Block();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ForImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Init Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__INIT_STATEMENTS = eINSTANCE.getFor_InitStatements();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__GUARD = eINSTANCE.getFor_Guard();

    /**
     * The meta object literal for the '<em><b>Progress Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__PROGRESS_STATEMENTS = eINSTANCE.getFor_ProgressStatements();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__BLOCK = eINSTANCE.getFor_Block();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.DoWhileImpl <em>Do While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.DoWhileImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getDoWhile()
     * @generated
     */
    EClass DO_WHILE = eINSTANCE.getDoWhile();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DO_WHILE__BLOCK = eINSTANCE.getDoWhile_Block();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DO_WHILE__GUARD = eINSTANCE.getDoWhile_Guard();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.IncrementImpl <em>Increment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.IncrementImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getIncrement()
     * @generated
     */
    EClass INCREMENT = eINSTANCE.getIncrement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INCREMENT__ID = eINSTANCE.getIncrement_Id();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.DecrementImpl <em>Decrement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.DecrementImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getDecrement()
     * @generated
     */
    EClass DECREMENT = eINSTANCE.getDecrement();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECREMENT__ID = eINSTANCE.getDecrement_Id();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ExpressionImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.LiteralImpl <em>Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.LiteralImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getLiteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL__VALUE = eINSTANCE.getLiteral_Value();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.NullImpl <em>Null</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.NullImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getNull()
     * @generated
     */
    EClass NULL = eINSTANCE.getNull();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.VarExpressionImpl <em>Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.VarExpressionImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getVarExpression()
     * @generated
     */
    EClass VAR_EXPRESSION = eINSTANCE.getVarExpression();

    /**
     * The meta object literal for the '<em><b>Parts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_EXPRESSION__PARTS = eINSTANCE.getVarExpression_Parts();

    /**
     * The meta object literal for the '<em><b>Array Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_EXPRESSION__ARRAY_INDEXES = eINSTANCE.getVarExpression_ArrayIndexes();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.ProcCallImpl <em>Proc Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.ProcCallImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getProcCall()
     * @generated
     */
    EClass PROC_CALL = eINSTANCE.getProcCall();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROC_CALL__ID = eINSTANCE.getProcCall_Id();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROC_CALL__ARGS = eINSTANCE.getProcCall_Args();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.TypeImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__ID = eINSTANCE.getType_Id();

    /**
     * The meta object literal for the '<em><b>Array Dims</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__ARRAY_DIMS = eINSTANCE.getType_ArrayDims();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.NewArrayImpl <em>New Array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.NewArrayImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getNewArray()
     * @generated
     */
    EClass NEW_ARRAY = eINSTANCE.getNewArray();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEW_ARRAY__TYPE = eINSTANCE.getNewArray_Type();

    /**
     * The meta object literal for the '<em><b>Array Dims</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEW_ARRAY__ARRAY_DIMS = eINSTANCE.getNewArray_ArrayDims();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.NewObjectImpl <em>New Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.NewObjectImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getNewObject()
     * @generated
     */
    EClass NEW_OBJECT = eINSTANCE.getNewObject();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NEW_OBJECT__TYPE = eINSTANCE.getNewObject_Type();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.IdentifierImpl <em>Identifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.IdentifierImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getIdentifier()
     * @generated
     */
    EClass IDENTIFIER = eINSTANCE.getIdentifier();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENTIFIER__ID = eINSTANCE.getIdentifier_Id();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.OrImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.XorImpl <em>Xor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.XorImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getXor()
     * @generated
     */
    EClass XOR = eINSTANCE.getXor();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XOR__LEFT = eINSTANCE.getXor_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XOR__RIGHT = eINSTANCE.getXor_Right();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.AndImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.EqualityImpl <em>Equality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.EqualityImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getEquality()
     * @generated
     */
    EClass EQUALITY = eINSTANCE.getEquality();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__LEFT = eINSTANCE.getEquality_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUALITY__OPERATOR = eINSTANCE.getEquality_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY__RIGHT = eINSTANCE.getEquality_Right();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.RelationImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__LEFT = eINSTANCE.getRelation_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATION__OPERATOR = eINSTANCE.getRelation_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__RIGHT = eINSTANCE.getRelation_Right();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.AdditionImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link pt.iscte.paddle.javali.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pt.iscte.paddle.javali.impl.MultiplicationImpl
     * @see pt.iscte.paddle.javali.impl.JavaliPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

  }

} //JavaliPackage
