/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.paddle.javali.Module#getConstants <em>Constants</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Module#getRecords <em>Records</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Module#getProcedures <em>Procedures</em>}</li>
 * </ul>
 *
 * @see pt.iscte.paddle.javali.JavaliPackage#getModule()
 * @model
 * @generated
 */
public interface Module extends EObject
{
  /**
   * Returns the value of the '<em><b>Constants</b></em>' containment reference list.
   * The list contents are of type {@link pt.iscte.paddle.javali.Constant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constants</em>' containment reference list.
   * @see pt.iscte.paddle.javali.JavaliPackage#getModule_Constants()
   * @model containment="true"
   * @generated
   */
  EList<Constant> getConstants();

  /**
   * Returns the value of the '<em><b>Records</b></em>' containment reference list.
   * The list contents are of type {@link pt.iscte.paddle.javali.Record}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Records</em>' containment reference list.
   * @see pt.iscte.paddle.javali.JavaliPackage#getModule_Records()
   * @model containment="true"
   * @generated
   */
  EList<Record> getRecords();

  /**
   * Returns the value of the '<em><b>Procedures</b></em>' containment reference list.
   * The list contents are of type {@link pt.iscte.paddle.javali.Procedure}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedures</em>' containment reference list.
   * @see pt.iscte.paddle.javali.JavaliPackage#getModule_Procedures()
   * @model containment="true"
   * @generated
   */
  EList<Procedure> getProcedures();

} // Module
