/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.paddle.javali.NewArray#getType <em>Type</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.NewArray#getArrayDims <em>Array Dims</em>}</li>
 * </ul>
 *
 * @see pt.iscte.paddle.javali.JavaliPackage#getNewArray()
 * @model
 * @generated
 */
public interface NewArray extends Expression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Identifier)
   * @see pt.iscte.paddle.javali.JavaliPackage#getNewArray_Type()
   * @model containment="true"
   * @generated
   */
  Identifier getType();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.NewArray#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Identifier value);

  /**
   * Returns the value of the '<em><b>Array Dims</b></em>' containment reference list.
   * The list contents are of type {@link pt.iscte.paddle.javali.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Dims</em>' containment reference list.
   * @see pt.iscte.paddle.javali.JavaliPackage#getNewArray_ArrayDims()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArrayDims();

} // NewArray
