/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.iscte.paddle.javali.JavaliPackage#getNull()
 * @model
 * @generated
 */
public interface Null extends Expression
{
} // Null
