/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#getComment <em>Comment</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#isStatic <em>Static</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#getRetType <em>Ret Type</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#isVoid <em>Void</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#getId <em>Id</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#getParams <em>Params</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.Procedure#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure()
 * @model
 * @generated
 */
public interface Procedure extends EObject
{
  /**
   * Returns the value of the '<em><b>Comment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comment</em>' attribute.
   * @see #setComment(String)
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_Comment()
   * @model
   * @generated
   */
  String getComment();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.Procedure#getComment <em>Comment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comment</em>' attribute.
   * @see #getComment()
   * @generated
   */
  void setComment(String value);

  /**
   * Returns the value of the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Static</em>' attribute.
   * @see #setStatic(boolean)
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_Static()
   * @model
   * @generated
   */
  boolean isStatic();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.Procedure#isStatic <em>Static</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Static</em>' attribute.
   * @see #isStatic()
   * @generated
   */
  void setStatic(boolean value);

  /**
   * Returns the value of the '<em><b>Ret Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ret Type</em>' containment reference.
   * @see #setRetType(Type)
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_RetType()
   * @model containment="true"
   * @generated
   */
  Type getRetType();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.Procedure#getRetType <em>Ret Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ret Type</em>' containment reference.
   * @see #getRetType()
   * @generated
   */
  void setRetType(Type value);

  /**
   * Returns the value of the '<em><b>Void</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Void</em>' attribute.
   * @see #setVoid(boolean)
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_Void()
   * @model
   * @generated
   */
  boolean isVoid();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.Procedure#isVoid <em>Void</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Void</em>' attribute.
   * @see #isVoid()
   * @generated
   */
  void setVoid(boolean value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' containment reference.
   * @see #setId(Identifier)
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_Id()
   * @model containment="true"
   * @generated
   */
  Identifier getId();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.Procedure#getId <em>Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' containment reference.
   * @see #getId()
   * @generated
   */
  void setId(Identifier value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link pt.iscte.paddle.javali.VarDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_Params()
   * @model containment="true"
   * @generated
   */
  EList<VarDeclaration> getParams();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Block)
   * @see pt.iscte.paddle.javali.JavaliPackage#getProcedure_Body()
   * @model containment="true"
   * @generated
   */
  Block getBody();

  /**
   * Sets the value of the '{@link pt.iscte.paddle.javali.Procedure#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Block value);

} // Procedure
