/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see pt.iscte.paddle.javali.JavaliPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
