/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali.impl;

import org.eclipse.emf.ecore.EClass;

import pt.iscte.paddle.javali.Break;
import pt.iscte.paddle.javali.JavaliPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Break</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BreakImpl extends StatementImpl implements Break
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BreakImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaliPackage.Literals.BREAK;
  }

} //BreakImpl
