/**
 * generated by Xtext 2.19.0
 */
package pt.iscte.paddle.javali.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import pt.iscte.paddle.javali.Expression;
import pt.iscte.paddle.javali.Identifier;
import pt.iscte.paddle.javali.JavaliPackage;
import pt.iscte.paddle.javali.NewArray;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>New Array</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link pt.iscte.paddle.javali.impl.NewArrayImpl#getType <em>Type</em>}</li>
 *   <li>{@link pt.iscte.paddle.javali.impl.NewArrayImpl#getArrayDims <em>Array Dims</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NewArrayImpl extends ExpressionImpl implements NewArray
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Identifier type;

  /**
   * The cached value of the '{@link #getArrayDims() <em>Array Dims</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArrayDims()
   * @generated
   * @ordered
   */
  protected EList<Expression> arrayDims;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NewArrayImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return JavaliPackage.Literals.NEW_ARRAY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Identifier getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Identifier newType, NotificationChain msgs)
  {
    Identifier oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, JavaliPackage.NEW_ARRAY__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(Identifier newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - JavaliPackage.NEW_ARRAY__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - JavaliPackage.NEW_ARRAY__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, JavaliPackage.NEW_ARRAY__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expression> getArrayDims()
  {
    if (arrayDims == null)
    {
      arrayDims = new EObjectContainmentEList<Expression>(Expression.class, this, JavaliPackage.NEW_ARRAY__ARRAY_DIMS);
    }
    return arrayDims;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case JavaliPackage.NEW_ARRAY__TYPE:
        return basicSetType(null, msgs);
      case JavaliPackage.NEW_ARRAY__ARRAY_DIMS:
        return ((InternalEList<?>)getArrayDims()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case JavaliPackage.NEW_ARRAY__TYPE:
        return getType();
      case JavaliPackage.NEW_ARRAY__ARRAY_DIMS:
        return getArrayDims();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case JavaliPackage.NEW_ARRAY__TYPE:
        setType((Identifier)newValue);
        return;
      case JavaliPackage.NEW_ARRAY__ARRAY_DIMS:
        getArrayDims().clear();
        getArrayDims().addAll((Collection<? extends Expression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case JavaliPackage.NEW_ARRAY__TYPE:
        setType((Identifier)null);
        return;
      case JavaliPackage.NEW_ARRAY__ARRAY_DIMS:
        getArrayDims().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case JavaliPackage.NEW_ARRAY__TYPE:
        return type != null;
      case JavaliPackage.NEW_ARRAY__ARRAY_DIMS:
        return arrayDims != null && !arrayDims.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //NewArrayImpl
