/*
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class JavaliProposalProvider extends AbstractJavaliProposalProvider {
}
