/*
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class JavaliRuntimeModule extends AbstractJavaliRuntimeModule {
	
}
